import { Provider } from "@/components/chakra-ui/provider";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Chakra UI Next.js Example",
  description: "Generated by create-next-app with Chakra UI",
};

export default function RootLayout(props: { children: React.ReactNode }) {
  const { children } = props;
  return (
    <html lang="ja" suppressHydrationWarning>
      <body>
        <Provider defaultTheme="light">{children}</Provider>
      </body>
    </html>
  );
}
